# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ee61bb83140d5a3c35033f59da914850262245aef90abf34cb4fd1f23e912ff060f26b0f93a7cf4258c4fcb31c06a970200c28f5debed93cb25360bd4994b8cf

test:
  secret_key_base: b5d7f9886b1ac294846bfd685034b993177ef307e90b31f56fa244b36cb01de1b139187b095b2e7afe6be4084b5bb181aff7fb189f53ef7b8e74694631ea14c9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
